version: '3.8'

services:
  react-dev:
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'

    expose:
      - 3000
    ports:
      - "3000:3000"
    stdin_open: true